### Get all events
GET http://localhost:3000/event


### Get event by id
GET http://localhost:3000/event/1234567890


### Get event by name
GET http://localhost:3000/event?name=John%20Doe


### Update event by id 
PUT  http://localhost:3000/event/1234567890

### Remove event by id
DELETE  http://localhost:3000/event/1234567890


### Add new event
POST http://localhost:3000/event
Content-Type: application/json
{
    "date": "04.08.2024",
    "hour": "20:00:00",
    "location": "Zapa Herzeliya",
    "city": "Herzeliya",
    "artist": "Natan Goshen",
    "image": "something.jpg",
    "_id": "1234567890",
}

###
POST http://localhost:3000/event


### Add new event
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email" : "tes12@test.com",
    "password" : "123456789"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email" : "test1@test.com",
    "password" : "123456789"
}